### ISSUE TITLE
Revision anteproyecto

### ISSUE THREAD

**Issue by AVegMor** [darkzpvp/forstAI#1]
Hola Víctor,

hemos estado revisando tu anteproyecto y hemos visto las siguientes cosas:

El esquema E/R es muy pobre. Entendemos que estás haciendo un e-commerce de suscripciones que tienen prompts??? 
Luego tienes que vas a dar 10 prompts pero tienes suscripciones de más prompts y no tienes una suscripción básica que entiendo que sería la de los 10 prompts porque no sé cómo vas a gestionar esos 10 prompts gratuitos.

¿Se van a guardar los prompts o las imágenes?

Es un poco batiburrillo, dale una vuelta y revísalo.

**Comment by darkzpvp** [comment]
Buenas noches

1Tabla de Usuarios:
• Campos: id_usuario (clave primaria), nombre, email, token y prompts_gratuitos
• Relación: Uno a Uno con la tabla de Suscripciones mediante una clave externa (id_suscripcion).
2. Tabla de Suscripciones:
• Campos: id_suscripcion (clave primaria), id_usuario (clave externa), tipo (básico, estándar, premium), prompts_disponibles.
• Relación: Uno a Uno con la tabla de Usuarios mediante una clave externa (id_usuario).
3. Tabla de Prompts:
• Campos: id_prompt (clave primaria), texto.
• Relación: Muchos a Uno con la tabla de Suscripciones mediante una clave externa (id_suscripcion).


Los 10 prompts gratuitos se incluirían en la tabla de usuarios.
El campo texto de la tabla prompts guardaría los prompts.

Este es el esquema que llevo pensando estos días. Lo que puse en el notion no era definitivo, ya que mediante avanzaba mi proyecto iba a cambiar cosas.

Gracias

Enviado desde mi iPhone


El 15 abr 2024, a las 20:09, AVegMor ***@***.***> escribió:

﻿

Hola Víctor,

hemos estado revisando tu anteproyecto y hemos visto las siguientes cosas:

El esquema E/R es muy pobre. Entendemos que estás haciendo un e-commerce de suscripciones que tienen prompts???
Luego tienes que vas a dar 10 prompts pero tienes suscripciones de más prompts y no tienes una suscripción básica que entiendo que sería la de los 10 prompts porque no sé cómo vas a gestionar esos 10 prompts gratuitos.

¿Se van a guardar los prompts o las imágenes?

Es un poco batiburrillo, dale una vuelta y revísalo.

**Comment by darkzpvp** [comment]
En la empresa me explicaron los observadores de eventos. Tengo pensado aplicarlos para mi caso. Por ejemplo,
Si el tipo de suscripción es “básico”, que la columna prompts_disponibles de tipo INT se establezca en 20. Luego, cada mes me gustaría que los prompts se pusieran a su valor, 20 en el caso de la suscripción básica, por lo que ahí usaría un trabajo programado para que se repita todos los meses
Enviado desde mi iPhone

El 15 abr 2024, a las 21:26, Víctor Valverde Olmedo ***@***.***> escribió:

﻿ Buenas noches

1Tabla de Usuarios:
• Campos: id_usuario (clave primaria), nombre, email, token y prompts_gratuitos
• Relación: Uno a Uno con la tabla de Suscripciones mediante una clave externa (id_suscripcion).
2. Tabla de Suscripciones:
• Campos: id_suscripcion (clave primaria), id_usuario (clave externa), tipo (básico, estándar, premium), prompts_disponibles.
• Relación: Uno a Uno con la tabla de Usuarios mediante una clave externa (id_usuario).
3. Tabla de Prompts:
• Campos: id_prompt (clave primaria), texto.
• Relación: Muchos a Uno con la tabla de Suscripciones mediante una clave externa (id_suscripcion).


Los 10 prompts gratuitos se incluirían en la tabla de usuarios.
El campo texto de la tabla prompts guardaría los prompts.

Este es el esquema que llevo pensando estos días. Lo que puse en el notion no era definitivo, ya que mediante avanzaba mi proyecto iba a cambiar cosas.

Gracias

Enviado desde mi iPhone


El 15 abr 2024, a las 20:09, AVegMor ***@***.***> escribió:

﻿

Hola Víctor,

hemos estado revisando tu anteproyecto y hemos visto las siguientes cosas:

El esquema E/R es muy pobre. Entendemos que estás haciendo un e-commerce de suscripciones que tienen prompts???
Luego tienes que vas a dar 10 prompts pero tienes suscripciones de más prompts y no tienes una suscripción básica que entiendo que sería la de los 10 prompts porque no sé cómo vas a gestionar esos 10 prompts gratuitos.

¿Se van a guardar los prompts o las imágenes?

Es un poco batiburrillo, dale una vuelta y revísalo.

**Comment by AVegMor** [comment]
Hola Victor, para poder llevar el seguimiento de tu proyecto, necesitamos que actualices el anteproyecto con la versión lo más definitiva posible de lo que vayas a hacer. Somos conscientes que el proyecto irá sufriendo cambios a lo largo de su desarrollo, pero es importante tener clara la idea inicial, para evitar improvisaciones y descentrarnos del punto principal.

**Comment by darkzpvp** [comment]
Hecho 👍
