### ISSUE TITLE
Revisión checkpoint 10 mayo.

### ISSUE THREAD

**Issue by AVegMor** [darkzpvp/forstAI#3]
Hola.

Lo primero que has entregado un día tarde el vídeo. Recuerda que tienes que completar la documentación. No veo el código de la parte servidor. 

Otros puntos que he visto:
- El carrito se pasa a 15 €
- A la hora de validar los datos introducidos en los formularios, también hay que validarlos a nivel de back (servidor) Las Requests que vimos en clase.
- En cuanto a BD las suscripciones deberían ser una tabla aparte con los 3 tipos y luego una tabla intermedia que enlace los usuarios con las suscripciones.
- No estas validando por ahora dni, tarjeta válida...
- Si vas mal de tiempo recorta en la página de administración.

Saludos.

**Comment by darkzpvp** [comment]
El código de la parte servidor está en la otra rama. Te envié un mensaje hace dos semanas para evitar confusiones, pero no sé si lo llegaste a ver.
Las suscripciones es una relación de una a una, ya que solo se permite una suscripción por usuario, y en el caso del DNI  y tarjeta no lo valido en el backend, ya que no lo almaceno en el servidor, solo en el cliente (no lo hice porque no vi apropiado almacenar esos datos sensibles en el servidor, sin embargo sí que lo hice con la información personal del usuario).

Seguiré tus indicaciones, muchas gracias

**Comment by AVegMor** [comment]
¿Me has añadido como colaboradora en esa rama?  No la veo

**Comment by rlopdav392** [comment]
Buenas Victor,

Solo comentarte que en el vídeo, echo en falta la parte del prototipado, explicar un poco esa parte.
Y dos cosillas más:

- Con respecto a la conexión de la parte frontend con el backend, veo en el bitácora de tareas, que comentas repetidamente que no hay casi documentación sobre ello, y has tenido que "buscarte la vida", está genial, que lo hayas sacado por tu cuenta, pero solo comentarte, que si lees los correos que os envío, en abril os pasé un proyecto entero fullstack donde se ve claramente la conexión del frontend con el backend haciendo uso de axios y de token bearer. Además, por si no se entendía el código, estuve grabando videotutoriales donde explico detalladamente todo el proyecto, y también os pasé un documento explicativo de cómo usar axios en react para este tema del token bearer, por si no teníais tiempo para ver los videotutoriales. Así, que si necesitas en algún momento ver uso de axios con bearer token, allí tienes toda la documentación.

- Con respecto a la parte desktop, acuérdate, que luego tienes que hacer una parte mobile con css puro y javascript nativo. Digo, para que no te organices los tiempos.

Rocío.

**Comment by darkzpvp** [comment]
@AVegMor Sí, te paso en link de la rama por si acaso https://github.com/darkzpvp/forstAI/tree/backendLaravel

**Comment by darkzpvp** [comment]
@rlopdav392 Buenas Rocío, no te preocupes, el problema no estaba contigo, el problema era más bien mío, ya que quería hacer algo que no sabía de qué forma, y era por la escasa documentación que hay en internet; lo único que encuentro son vídeos de indios y todo mal explicado y es respecto a la verificación de correos con Laravel y el reseteo de contraseñas con token, pero no precisamente lo que tú ofreciste, que fueron vídeos de Youtube muy currados, de hecho hiciste el mismo curso de Udemy que yo.😊

Lo del figma estoy en ello, tengo una parte completa, la otra versión estará al 50% más o menos

**Comment by darkzpvp** [comment]
@AVegMor Lo de la suscripción en el carrito de compras lo solucionaré lo antes posible (hoy o mañana) se ve que en la primera página puse la lógica, pero me faltó en la otra. Y trataré de tener completo todo, incluso lo de la administración.

Por cierto, ¿pudiste entrar en la rama? Si te sigue dando problemas puedo ponerlo todo en la misma, lo hice para que sea menos lío y separar las partes 👍

**Comment by AVegMor** [comment]
Hola de nuevo.
Ya he podido ver la rama. He visto que ya tienes la api con el laravel sanctum y has diferenciado entre los endpoints que requieren inicio de sesión y los que no. Lo llevas muy avanzado.

- ForgotPasswordRequest no tiene ninguna validación. ¿Esto es así o que lo tienes pendiente?
- Intenta ser consistente en el nombre de las clases, unas están en español y otras en inglés: 
![image](https://github.com/darkzpvp/forstAI/assets/144597519/01decfe3-9b14-4132-84e0-6fc2fe880575)

- Lo mismo con el nombre de las funciones: 
![image](https://github.com/darkzpvp/forstAI/assets/144597519/f5191b22-d1c9-4c8a-b370-3374a4b0fa29)

- Se consistente también en las urls que estás publicando, también tienes en español y en inglés. Hazlo todo o en inglés o en español, pero no mezcles. Además tienes una url separada por guión bajo y otras por guión normal, sé consistente.
![image](https://github.com/darkzpvp/forstAI/assets/144597519/a9defdc4-76a0-4b22-9a97-65196065bd42)


- No has añadido aún ningún test. Recuerda que esta parte es muy importante para detectar posibles bugs antes que lo haga el cliente o usuario final. Cuantos más completos sean los tests mejor.

Buen trabajo.

**Comment by darkzpvp** [comment]
![image](https://github.com/darkzpvp/forstAI/assets/67244518/87b9e809-abb3-4392-9386-da9053deb5b1)
Ayer se me olvidó subir el último commit, en realidad tengo 8 endpoints más. Me quedan 5 para el panel de administración y alguno que otro seguramente también, para pintar en el cliente la información del usuario. Una pregunta, basta con hacer los tests de la autenticación y otros 5 que incluya (GET, DELETE, POST GET POR ID y PUT) o tengo que hacer todos? Es que hice cálculos y son más de 30 tests, no creo que me de tiempo

Por otro lado, vale, cambiaré la nomenclatura para hacerlo todo más consistente, y en este caso decidí meter la validación de Forgot Password en el mismo controlador, por lo que el Request ha quedado en desuso (ya está borrado)

**Comment by AVegMor** [comment]
En cuanto a los tests, ten en cuenta que cuanto más completa sea tu aplicación mejor
